# One entry per distinct sheet. Duplicate scans (0020, 0024 = 0008) are omitted.
# Class colours are seeds taken from the *map* pigments as they read in the slide scans
# (his light-yellow marker reads as a cream wash, his orange marker as a saturated yellow).
# kind: 'fill' (marker fill) or 'line' (marker stroke / outline).
DARK_RED="#b5453a"; ORANGE_FILL="#ebb95e"; CREAM="#f2e3c2"; RED_ORANGE="#cc6a3f"; SAT_YELLOW="#e4b061"
NAVY="#304184"; TEAL="#4f6976"; PURPLE="#5a3f8a"; DARK_BROWN="#7a3b2a"; ORANGE_LINE="#d1723e"; YELLOW_LINE="#e0b040"

SHEETS=[
 dict(num="0008", group="survey", order=1,
      he="מערכת הדרכים 1967", en="Road system, 1967",
      legend=(20,1320,310,1570),
      classes=[("vehicle","#b55b54","line","רכב","Vehicles"),
               ("ped_main","#c87856","line","הולכי רגל (ראשי)","Pedestrians, main"),
               ("ped_sec","#dfae6d","line","הולכי רגל (משני)","Pedestrians, secondary")]),
 dict(num="0013", group="survey", order=2,
      he="גובה מבנים ברובע (1967)", en="Building heights in the Quarter, 1967",
      legend=(60,1290,290,1560),
      classes=[("h34",DARK_RED,"fill","3–4 קומות","3–4 floors"),
               ("h23",ORANGE_FILL,"fill","2–3 קומות","2–3 floors"),
               ("h12",CREAM,"fill","1–2 קומות","1–2 floors")]),
 dict(num="0014", group="survey", order=3,
      he="שטחים פנויים (1967)", en="Vacant areas, 1967",
      legend=(80,1320,340,1570),
      classes=[("destroyed",RED_ORANGE,"fill","הרוס","Destroyed"),
               ("partial",SAT_YELLOW,"fill","הרוס חלקי","Partly destroyed"),
               ("empty","#4f606d","fill","ריק","Empty")]),
 dict(num="0015", group="survey", order=4,
      he="בעלויות לפני ההפקעה", en="Ownership before the expropriation",
      legend=(15,1250,300,1630),
      classes=[("jewish",NAVY,"fill","רכוש יהודי","Jewish property"),
               ("waqf","#bd4a3d","fill","וקף מוסלמי","Muslim waqf"),
               ("family_waqf",ORANGE_FILL,"fill","וקף מוסלמי משפחתי","Family Muslim waqf"),
               ("muslim_private",CREAM,"fill","רכוש מוסלמי פרטי","Private Muslim property"),
               ("church",PURPLE,"line","רכוש כנסיות","Church property"),
               ("municipal",TEAL,"fill","רכוש עיריה או ממשלה","Municipal or government property")]),
 dict(num="0018", group="survey", order=5,
      he="חנויות ובתי מלאכה", en="Shops and workshops",
      legend=(20,1360,310,1560),
      classes=[("shops","#c0442c","line","חנויות ובתי מלאכה","Shops and workshops")]),
 dict(num="0016", group="past", order=6,
      he="תחום הרובע (בעבר)", en="Extent of the Quarter in the past",
      legend=(0,1120,240,1480),
      classes=[("extent_1929",ORANGE_LINE,"line","1929","Boundary, 1929"),
               ("extent_1936",SAT_YELLOW,"line","1936","Boundary, 1936"),
               ("institutions",DARK_BROWN,"fill","מוסדות","Institutions")]),
 dict(num="0019", group="past", order=7,
      he="מוסדות יהודיים ברובע (בעבר)", en="Jewish institutions in the Quarter, past",
      legend=(10,1250,270,1630),
      classes=[("synagogue",DARK_BROWN,"fill","בית כנסת","Synagogue"),
               ("midrash",ORANGE_FILL,"fill","בית מדרש","Beit midrash"),
               ("hospital",CREAM,"fill","בית חולים","Hospital"),
               ("kotel_route","#d6813a","line","(מסלול לכותל)","(route to the Western Wall)")]),
 dict(num="0021", group="plan", order=8,
      he="סכמת התכנון", en="Planning scheme",
      legend=(60,1260,300,1420),
      classes=[("ring_road","#b74b3b","line","דרך רכב","Vehicular ring"),
               ("ped_spine","#c9a8c4","line","צירי הולכי רגל","Pedestrian spines"),
               ("plaza","#7981b8","fill","כיכרות","Open squares"),
               ("descent","#4a3c6e","line","ירידה לכותל","Descent to the Western Wall")]),
 dict(num="0017", group="plan", order=9,
      he="תכנית שימור", en="Preservation plan",
      legend=(60,1240,290,1560),
      classes=[("preserve","#7d97cf","line","לשימור","To preserve"),
               ("rehab","#9e5448","line","לשיקום","To rehabilitate"),
               ("special","#b83f1d","fill","ערך מיוחד","Special value"),
               ("facade","#3b3566","line","חזית מיוחדת","Special façade")]),
 dict(num="0025", group="plan", order=10,
      he="תכנון דרכים חדשות", en="Land use and new roads",
      legend=(20,1120,230,1570),
      classes=[("paths",YELLOW_LINE,"line","דרכים","Paths"),
               ("removed","#b0402a","fill","(להריסה)","(to be removed)")]),
 dict(num="0028", group="plan", order=11,
      he="תכנון דרכים", en="Roads plan",
      legend=(50,1150,270,1560),
      classes=[("paths","#e4c878","line","דרכים ושבילים (צהוב ובז')","Roads and paths (yellow and tan)"),
               ("gardens","#9fbf6a","fill","גינות","Gardens")]),
 dict(num="0027", group="plan", order=12,
      he="גבהים מתוכננים", en="Planned heights",
      legend=(20,1040,290,1570),
      classes=[("p4","#2d2649","fill","4 קומות","4 floors"),
               ("p3","#9a3a30","fill","3 קומות","3 floors"),
               ("p12","#f2d066","fill","1–2 קומות","1–2 floors")]),
 dict(num="0031", group="plan", order=13,
      he='אתר פרויקט "החורבה"', en='The "Hurva" project site',
      legend=(0,1250,250,1650),
      params=dict(thick_k=5,fill_base_handicap=0.0,line_base_handicap=0.0,thick_from_dark=0.5),
      classes=[("site","#2a2a5a","line","אתר","Site outline")]),
 dict(num="0032", group="plan", order=14,
      he="תכנון: שלבי ביצוע", en="Phasing",
      legend=(0,1120,160,1780),
      classes=[("parking","#c8602a","fill","חניון","Parking"),
               ("vehicle",YELLOW_LINE,"line","רכב","Vehicle route"),
               ("today","#a0503a","line","מסלול כיום","Current route (dashed)")]),
]
GROUPS={"survey":("הסקר, 1967","The survey, 1967"),"past":("בעבר","The past"),"plan":("התכנית","The plan")}
